import {
	adidasCropTop,
	adidasJoggingShoe,
	crosshatchGlass,
	loboutin,
	LVBag,
	LVChain,
	NikeJacket,
	PantTrouser,
	PetiteDress,
	PetiteJean,
	TedBag,
	NikeVest,
	WineDress,
	colorJacket,
} from "assets/images";

export const ProductPageProducts = [
	{
		Title: "Adidas",
		SubTitle: "Black Crop Hoodie",
		Price: "46500",
		image: adidasCropTop,
	},
	{
		Title: "Petite Dress",
		SubTitle: "Wrap mini dress in mixed ditsy floral",
		Price: "46500",
		image: PetiteDress,
	},
	{
		Title: "Ted Bag",
		SubTitle: "Soocon crosshatch large icon bag",
		Price: "46500",
		image: TedBag,
	},
	{
		Title: "Nike Jacket",
		SubTitle: "Woven colour block vest in beige",
		Price: "46500",
		image: NikeJacket,
	},
	{
		Title: "Pant Trousers",
		SubTitle: "Wrap mini dress in mixed ditsy floral",
		Price: "46500",
		image: PetiteJean,
	},
	{
		Title: "Red Loboutin",
		SubTitle: "Soocon crosshatch large icon bag",
		Price: "46500",
		image: loboutin,
	},
	{
		Title: "Nike Vest",
		SubTitle: " Woven colour block vest in beige",
		Price: "46500",
		image: NikeVest,
	},
	{
		Title: "Fenty Pink Shades",
		SubTitle: " Woven colour block vest in beige",
		Price: "46500",
		image: crosshatchGlass,
	},
	{
		Title: "Unisex Nike Jeans",
		SubTitle: "Wrap mini dress in mixed ditsy floral",
		Price: "46500",
		image: PetiteJean,
	},
	{
		Title: "Nike wine dress",
		SubTitle: "Woven colour block vest in beige",
		Price: "46500",
		image: WineDress,
	},
	{
		Title: "Adidas running shoe",
		SubTitle: "Wrap mini dress in mixed ditsy floral",
		Price: "46500",
		image: adidasJoggingShoe,
	},
	{
		Title: "Adidas Pant Trousers",
		SubTitle: "Wrap mini dress in mixed ditsy floral",
		Price: "46500",
		image: PantTrouser,
	},
	{
		Title: "Louis Vuitton Bag",
		SubTitle: "Soocon crosshatch large icon bag",
		Price: "46500",
		image: LVBag,
	},
	{
		Title: "Nike Multicolor Jacket",
		SubTitle: "Woven colour block vest in beige",
		Price: "46500",
		image: colorJacket,
	},
	{
		Title: "Louis Vuitton Chain",
		SubTitle: "Woven colour block vest in beige",
		Price: "46500",
		image: LVChain,
	},
];
